config/routes.rb
Hatio::Application.routes.draw do

  resources :domains do
    member do
      post :enter
    end
    
    collection do
      get :change
      post :update_multiple
      post :export
    end
  end
  
  devise_for :users
  
  devise_scope :user do
    post "add_user", :to => "users"
    post "users_update_multiple", :to => "users"
    post "import_users", :to => "users"
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end
  
  resources :users, :only => [:show, :index, :edit, :update]  
    
  authenticated :user do 
    root :to => 'home#std'
  end

  match 'test' => 'home#test'
  
  match 'ops' => 'home#ops'
  
  match 'std' => 'home#std'
  
  match 'cfinstall' => 'home#cfinstall'
  
  match 'cfdownload' => 'home#cfdownload'
  
  match 'spc_chart' => 'home#spc_chart'
  
  root :to => "welcome#index"
  

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  
  attr_accessible :name, :description, :timezone, :system_flag, :creator_id, :updater_id
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  
  # HAS_MANY BEGIN BLOCK DON'T REMOVE
  
  stampable
  meaningful_id [:name]
  
  def self.system_domain
    Domain.find_by_system_flag(true) || Domain.first
  end
  
  def clone_roles(from_domain, to_domain)
    from_domain.roles.each do |from_role|
      to_attributes = from_role.attributes
      to_attributes.delete('domain_id')
      to_role = to_domain.roles.create(to_attributes)
      
      #clone_permissions(from_role, to_role)
      #clone_role_users(from_role, to_role)
    end
  end  
  
  def clone_system_domain
    system = Domain.system_domain    
    clone_roles(system, self)
  end
  
  #
  # Pluggable model dinamic loading
  #
  Hatio::PluggableSpot::DOMAIN_MODEL_PLUGGABLES.each do |pluggable_code|
    self.class_eval &pluggable_code
  end
  
end

app/controllers/domains_controller.rb
class DomainsController < InheritedResources::Base
  
  respond_to :html, :xml, :json
  before_filter :authenticate_user!
  
  def index
    @domains = Domain.all
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @domains }
      format.json { render :json => { :success => true, :total => @domains.size, :items => @domains } }
    end
  end
  
  def change
    @domains = Domain.all
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @domains }
      format.json { render :json => { :success => true, :total => @domains.size, :items => @domains } }
    end
  end
  
  def enter
    session[:current_domain_id] = params[:id]
        
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Domain was successfully changed.' }
      format.json { render :json => { :success => true, :msg => 'Domain was successfully changed!' } }
    end
  end
  
  def new
    @edit_domain = Domain.new
  end

  def show
    @show_domain = Domain.find(params[:id])
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @show_domain }
      format.json { render :json => @show_domain }
    end
  end

  def edit
    @edit_domain = Domain.find(params[:id])
  end
  
  def update
    update_domain = Domain.find(params[:id])
    result = false
    
    if(params[:domain])
      result = update_domain.update_attributes(params[:domain])
    else
      update_domain.name = params[:name]
      update_domain.description = params[:description]
      update_domain.timezone = params[:timezone]
      update_domain.system_flag = params[:system_flag]
      result = update_domain.save!
    end    

    respond_to do |format|
      if result
        format.html { redirect_to domains_path, notice: 'Domain was successfully updated.' }
        format.json { render :json => {:success => true, :msg => 'Domain was successfully updated!', :item => update_domain} }
      else
        format.html { render action: "edit" }
        format.json { render json: update_domain.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create    
    create_domain = nil
    if(params[:domain])
      create_domain = Domain.new(params[:domain])
    else
      create_domain = Domain.new      
      create_domain.name = params[:name]
      create_domain.description = params[:description]
      create_domain.timezone = params[:timezone]
      create_domain.system_flag = params[:system_flag]      
    end
      
    respond_to do |format|
      if create_domain.save
        format.html { redirect_to domains_path, notice: 'Domain was successfully created.' }
        format.json { render :json => {:success => true, :msg => 'Domain was successfully created!', :item => create_domain} }
      else
        format.html { render action: "new" }
        format.json { render json: create_domain.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    domain = Domain.find(params[:id])
    domain.destroy
    
    respond_to do |format|
      format.html { redirect_to domains_path, notice: 'Domain was successfully destroyed!' }
      format.json { render :json => {:success => true, :msg => 'Domain was successfully destroyed!'} }
    end
  end
  
  def update_multiple
    data_list = JSON.parse params[:multiple_data]
    delete_list, update_list, create_list = [], [], [];

    data_list.each do |data|
      cud_flag = data.delete('_cud_flag_')
      if(cud_flag == "d")
        delete_list << data['id']
      elsif(cud_flag == "u")
        update_list << data
      elsif(cud_flag == "c")
        create_list << data
      end
    end
          
    # 1. delete
    Domain.destroy(delete_list) unless delete_list.empty?

    # 2. update
    update_list.each do |data|
      domain = Domain.find(data.delete('id'))
      if domain
        data.delete('creator_id')
        data.delete('created_at')
        data.delete('updater_id')
        data.delete('updated_at')
        domain.update_attributes(data)
      end
    end if update_list

    # 3. create
    create_list.each do |data|
      data.delete('id')
      data.delete('creator_id')
      data.delete('created_at')
      data.delete('updater_id')
      data.delete('updated_at')        
      Domain.create!(data)
    end if create_list
  end
  
  def export
    @export_data = JSON.parse(params[:xlsGridInfo])
    @headers = @export_data.shift
    
    respond_to do |format|
      format.json { render :json => @export_data }
      format.xml { render :xml => @export_data }
      format.xls
    end
  end
  
end

app/views/domains/_form.html.erb
<%= form_for @edit_domain, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timezone, :class => 'control-label' %>
    <div class="controls">
	  <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones, :include_blank => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :system_flag, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :system_flag, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                domains_path, :class => 'btn' %>
  </div>
<% end %>

app/views/domains/change.html.erb
<%- model_class = Domain -%>
<div class="page-header">
  <h1>Change Domain</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:timezone) %></th>
      <th><%= model_class.human_attribute_name(:system_flag) %></th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.id %></td>
        <td><%= domain.name %></td>
        <td><%= domain.description %></td>
        <td><%= domain.timezone %></td>
        <td><%= domain.system_flag %></td>
        <td>
          <%= link_to 'enter', enter_domain_path(domain), :method => 'put', :class => 'btn btn-mini' if(domain.id != @domain.id) %>
		  <%= 'Current Domain' if(domain.id == @domain.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/domains/edit.html.erb
<%- model_class = Domain -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/domains/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
	<% @headers.each do |name, value| %>
        <Cell><Data ss:Type="String"><%= value %></Data></Cell>
	<% end %>
      </Row>
    <% @export_data.each do |data| %>
      <Row>
		<% @headers.each do |name, value| %>
		<Cell><Data ss:Type="String"><%= data[name] %></Data></Cell>
		<% end %>        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/domains/index.html.erb
<%- model_class = Domain -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:timezone) %></th>
      <th><%= model_class.human_attribute_name(:system_flag) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= link_to domain.id, domain_path(domain) %></td>
        <td><%= domain.name %></td>
        <td><%= domain.description %></td>
        <td><%= domain.timezone %></td>
        <td><%= domain.system_flag %></td>
        <td><%= domain.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_domain_path(domain), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      domain_path(domain),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_domain_path,
            :class => 'btn btn-primary' %>

app/views/domains/new.html.erb
<%- model_class = Domain -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/domains/show.html.erb
<%- model_class = Domain -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @show_domain.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @show_domain.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timezone) %>:</strong></dt>
  <dd><%= @show_domain.timezone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:system_flag) %>:</strong></dt>
  <dd><%= @show_domain.system_flag %></dd>
  <dt><strong><%= model_class.human_attribute_name(:creator_id) %>:</strong></dt>
  <dd><%= @show_domain.creator_name if @show_domain.creator %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updater_id) %>:</strong></dt>
  <dd><%= @show_domain.updater_name if @show_domain.updater %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @show_domain.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
  <dd><%= @show_domain.updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              domains_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_domain_path(@show_domain), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              domain_path(@show_domain),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>